linters-settings:
# this can be uncommented if GC04 feels too restrictive
  # gosec:
  #   settings:
  #     exclude: -G204
  lll:
    line-length: 950
  maligned:
    suggest-new: true
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped


linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - errcheck
    - errorlint
    - errname
    - errorlint
    - errchkjson
    - exhaustive
    - funlen
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - nakedret
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gofumpt
    - grouper
    - wrapcheck
    - bidichk
    - durationcheck
    - forcetypeassert

  # (optional)
    - asciicheck
    # - gochecknoglobals
    # - gocognit
    - godot
    - godox
    # - goerr113
    - maligned
    - nestif
    - prealloc
    # - testpackage
    # - wsl
